### PR TITLE
Corrections package path

### PR DESCRIPTION
**Pull request by lechnerc77**
This pull request contains a proposed change to solve issue #1 . It contains the adjustment in the `README.md` as well as in the corresponding files of the examples folder to point to the published npm package `@aaronpowell/azure-functions-nodejs-openapi`.

I also added an addition to the README for the runtime that should be used in accordance to the settings in the `host.json` file

### CODE REVIEW

**Comment by aaronpowell** [comment]
I'd prefer to leave the npm references as `file:` ones rather than pinned versions, that was the samples are always pointing to the current local revs

**Comment by lechnerc77** [comment]
I get your point from the perspective of developing the npm module, but have a different opinion from the perspective of a developer that wants to use the package and wants to get some insights via the examples. 
Nevertheless, happy to remove the change from the pull request, however the current setup does not work for me: I will detail the error description a new issue as issue #1 is targeting the README.md.
In addition any feedback to changes in the `README.md`?

**Comment by aaronpowell** [comment]
Yeah, need to fix the package name as it's used, it's a hold over from when it was a prototype and not published under my scope.

**Comment by lechnerc77** [comment]
I'll close this one and re-start to have a clean PR for the README correction

**Pull request closed without merging**
